name: PR

on:
  pull_request_target:
#  pull_request:
    branches: [main]
    types:
      - labeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: ready_for_review
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
  publish:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Patch URL
        run: |
          sed -i "s#baseUrl: '/test-action-token/'#baseUrl: '/test-action-token/pr-${{ github.event.number }}/'#" docusaurus.config.js
          cat docusaurus.config.js | grep baseUrl

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Test Security
        run: uname
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.EVN_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-${{ github.event.number }}
